# Generated by Django 3.2.13 on 2024-02-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('resumen', models.TextField()),
            ],
        ),
    ]
